---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-amzn-apigw-ingress-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-amzn-apigw-ingress-controller-manager-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-amzn-apigw-ingress-controller
  namespace: default
